services:
  - type: web
    name: sih-trusteye-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python backend.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
